version: '3.0'
services:
  web:
    image: mrupsidown/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
volumes:
  db-data: 